apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
  labels:
    app: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
        - name: devsecops
          image: VAL_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 4040
          env:
            - name: MONGO_HOST
              value: VAL_MONGO_HOST
             name: TEST_ENV
              value: 2002